# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333743b78bffa1c25abf118ab281d128c8d4d95e63457f4eece16f74c508ae236479ffe42dc677673b7e130dfc4cdcca0e1cdd68988c6c4d63f2792cb5ae8971

test:
  secret_key_base: b75293f374320f1b3c9365b61a3555769b77422a8342cb5657848b926a188d26af71c8c872e31906c28e1f3b4f42482eb9f9a03aeef72d8ff9368501f084c111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
